// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slgdrkecgowdgdsbzmhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsZ2Rya2VjZ293ZGdkc2J6bWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxOTEzNTksImV4cCI6MjA3Nzc2NzM1OX0.hgKR8Ooth-T0PtvOx7J6OPA_NxEugBO-rQ9N24ScpZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});